/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.coalvalue.domain.json;


public class AccessTokenEventJson {

    public String AppId;
    public String AppSecret;
    public Integer ExpiresIn;
    public Long ReveiveTime;
    public String Token;

    /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccessTokenEventJson() {}


    public String Behavior;
    ;     // 用户行为, 包括("pv", "buy", "cart", "fav")
    public Long Timestamp;

   /* public WeixinEventJson(MessageEvent value) {
        this.OpenId = value.getOpenId();

        this.CompanyId = value.getCompanyId();
        this.Id = value.getId();
        this.Behavior = "Create";
        Timestamp = LocalDateTime.now().toInstant(ZoneOffset.UTC).toEpochMilli();

  }*/






}
