/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.coalvalue.domain.json;


import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


public class WeixinRequestMessageTypeEvent_Scan_ResultJson {

    public String Info ;
    public String AppId;
    public String OpenId;
    public String Ttype;
    public String status;

    public String Key;
    public Boolean Subscribe;
    public String ObjectId
            ;


    /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeixinRequestMessageTypeEvent_Scan_ResultJson() {}
    /** Totla number of items in the order */


    public String Behavior;
    ;     // 用户行为, 包括("pv", "buy", "cart", "fav")
    public Long Timestamp;


    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }

}
