/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.coalvalue.domain.json;


import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


public class WeixinEventJson {

    public String AppId;

    /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeixinEventJson() {}
    /** Totla number of items in the order */
     public String OpenId;
    /** Id of the customer */
    /** Id of the supplier */
     public String AccessToken;
    /** First Name of Customer */

    /** First Name of Customer */

    public Object Event;


     public String Id;

    public String Behavior;
    ;     // 用户行为, 包括("pv", "buy", "cart", "fav")
    public Long Timestamp;

   /* public WeixinEventJson(MessageEvent value) {
        this.OpenId = value.getOpenId();

        this.CompanyId = value.getCompanyId();
        this.Id = value.getId();
        this.Behavior = "Create";
        Timestamp = LocalDateTime.now().toInstant(ZoneOffset.UTC).toEpochMilli();

  }*/

    public String getOpenId() {
        return OpenId;
    }

    public void setOpenId(String openId) {
        OpenId = openId;
    }

    public String getAccessToken() {
        return AccessToken;
    }

    public void setAccessToken(String accessToken) {
        AccessToken = accessToken;
    }

    public Object getEvent() {
        return Event;
    }

    public void setEvent(Object event) {
        Event = event;
    }

    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    public String getBehavior() {
        return Behavior;
    }

    public void setBehavior(String behavior) {
        Behavior = behavior;
    }

    public Long getTimestamp() {
        return Timestamp;
    }

    public void setTimestamp(Long timestamp) {
        Timestamp = timestamp;
    }


    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }

    public void setAppId(String appId) {
        this.AppId = appId;
    }

    public String getAppId() {
        return AppId;
    }
}
