/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.coalvalue.domain.json;


import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


public class WeixinQrcodeEventJson {

    public String AppId;


    private Integer scanId;


    private String Ttype;
    private String status;

    private Integer subScene;

    private String url;
    private String content;

    private String ticket;

    private String itemType;
    private String objectUuid;

    private String qrCode;
    private String id;
    private String temporaryOrPermanent;


    /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeixinQrcodeEventJson() {}
    /** Totla number of items in the order */


    public String Behavior;
    ;     // 用户行为, 包括("pv", "buy", "cart", "fav")
    public Long Timestamp;

    public Integer getScanId() {
        return scanId;
    }

    public void setScanId(Integer scanId) {
        this.scanId = scanId;
    }

    public String getTtype() {
        return Ttype;
    }

    public void setTtype(String ttype) {
        Ttype = ttype;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getSubScene() {
        return subScene;
    }

    public void setSubScene(Integer subScene) {
        this.subScene = subScene;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTicket() {
        return ticket;
    }

    public void setTicket(String ticket) {
        this.ticket = ticket;
    }

    public String getItemType() {
        return itemType;
    }

    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    public String getObjectUuid() {
        return objectUuid;
    }

    public void setObjectUuid(String objectUuid) {
        this.objectUuid = objectUuid;
    }

    public String getQrCode() {
        return qrCode;
    }

    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    public String getBehavior() {
        return Behavior;
    }

    public void setBehavior(String behavior) {
        Behavior = behavior;
    }

    public Long getTimestamp() {
        return Timestamp;
    }

    public void setTimestamp(Long timestamp) {
        Timestamp = timestamp;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }

    public void setAppId(String appId) {
        this.AppId = appId;
    }

    public String getAppId() {
        return AppId;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setTemporaryOrPermanent(String temporaryOrPermanent) {
        this.temporaryOrPermanent = temporaryOrPermanent;
    }

    public String getTemporaryOrPermanent() {
        return temporaryOrPermanent;
    }
}
